<?php

namespace AppBundle\Repository;

/**
 * CompteSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
